#!/bin/bash
#===============================================================================
# MQ CMDB Automation System - Pipeline Runner Script
#
# This script runs the complete MQ CMDB pipeline including:
#   1. Database export (db_export.py)
#   2. Processing pipeline (orchestrator.py)
#
# Usage: ./run_pipeline.sh [OPTIONS]
#
# Options:
#   --skip-export      Skip database export, use existing data
#   --diagrams-only    Only regenerate diagrams (skip data processing)
#   --dry-run          Show what would be executed without running
#   --verbose          Enable verbose output
#   --help             Show this help message
#
# Environment Variables:
#   UnlockKey            Master password for encrypted credentials (CI/CD variable)
#   DB_MASTER_PASSWORD   Alternative to UnlockKey (for local use)
#   MQCMDB_HOME          Installation directory (default: script directory)
#   MQCMDB_PROFILE       Database profile name (default: production)
#
# Email Notification Variables (optional):
#   EMAIL_ENABLED        Set to 'true' to enable email notifications
#   EMAIL_RECIPIENTS     Comma-separated list of recipient addresses
#   EMAIL_CONFIG_FILE    Path to email config INI file
#   SMTP_SERVER          SMTP server hostname
#   SMTP_PORT            SMTP server port (default: 25)
#   SMTP_USER            SMTP username for authentication
#   SMTP_PASSWORD        SMTP password for authentication
#   SMTP_FROM            Sender email address
#   SMTP_USE_TLS         Set to 'true' for STARTTLS
#
#===============================================================================

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# Script configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MQCMDB_HOME="${MQCMDB_HOME:-$(dirname "$SCRIPT_DIR")}"
MQCMDB_PROFILE="${MQCMDB_PROFILE:-production}"

# Flags
SKIP_EXPORT=false
DIAGRAMS_ONLY=false
DRY_RUN=false
VERBOSE=false

# Runtime variables
LOG_DIR="$MQCMDB_HOME/logs"
LOG_FILE=""
START_TIME=""
EXIT_CODE=0

#-------------------------------------------------------------------------------
# Functions
#-------------------------------------------------------------------------------

print_banner() {
    # Banner is generated by Python setup_logging and written to the log file.
    # Here we just print a short header to the console.
    echo -e "${CYAN}"
    python3 -c "from utils.logging_config_original import generate_ascii_art; [print(line) for line in generate_ascii_art('MQ CMDB')]" 2>/dev/null || echo "  MQ CMDB Pipeline Runner"
    echo ""
    echo -e "  MQ CMDB HIERARCHICAL AUTOMATION SYSTEM"
    echo -e "  Pipeline Runner v1.0"
    echo -e "${NC}"
}

log() {
    local level="$1"
    shift
    local message="$*"
    local timestamp=$(date '+%Y-%m-%d %H:%M:%S')

    case "$level" in
        INFO)  color="${GREEN}" ;;
        WARN)  color="${YELLOW}" ;;
        ERROR) color="${RED}" ;;
        STEP)  color="${BLUE}" ;;
        *)     color="${NC}" ;;
    esac

    # Console output
    echo -e "${color}[$level]${NC} $message"

    # File output (without colors)
    if [ -n "$LOG_FILE" ]; then
        echo "[$timestamp] [$level] $message" >> "$LOG_FILE"
    fi
}

log_info()  { log "INFO" "$@"; }
log_warn()  { log "WARN" "$@"; }
log_error() { log "ERROR" "$@"; }
log_step()  { echo ""; log "STEP" "$@"; echo "------------------------------------------------------------------------"; }

show_help() {
    cat << EOF
MQ CMDB Pipeline Runner

Usage: $(basename "$0") [OPTIONS]

Options:
  --skip-export      Skip database export, use existing data
  --diagrams-only    Only regenerate diagrams (skip data processing)
  --dry-run          Show what would be executed without running
  --verbose          Enable verbose output
  --help             Show this help message

Environment Variables:
  DB_MASTER_PASSWORD   Master password for encrypted credentials (required)
  MQCMDB_HOME          Installation directory (default: $MQCMDB_HOME)
  MQCMDB_PROFILE       Database profile name (default: production)

Email Notification Variables (optional):
  EMAIL_ENABLED        Set to 'true' to enable email notifications
  EMAIL_RECIPIENTS     Comma-separated list of recipient addresses
  EMAIL_CONFIG_FILE    Path to email config INI file (e.g., /etc/mqcmdb/email_config.ini)
  SMTP_SERVER          SMTP server hostname
  SMTP_PORT            SMTP server port (default: 25)
  SMTP_USER            SMTP username for authentication
  SMTP_PASSWORD        SMTP password for authentication
  SMTP_FROM            Sender email address
  SMTP_USE_TLS         Set to 'true' for STARTTLS

Examples:
  # Full pipeline run (using UnlockKey - recommended for CI/CD)
  export UnlockKey='your_password'
  ./run_pipeline.sh

  # Alternative: using DB_MASTER_PASSWORD directly
  export DB_MASTER_PASSWORD='your_password'
  ./run_pipeline.sh

  # Skip export, use existing data
  ./run_pipeline.sh --skip-export

  # Regenerate diagrams only
  ./run_pipeline.sh --diagrams-only

  # With email notifications
  export UnlockKey='your_password'
  export EMAIL_ENABLED=true
  export EMAIL_RECIPIENTS='ops@company.com,team@company.com'
  export SMTP_SERVER='smtp.company.com'
  export SMTP_FROM='mqcmdb@company.com'
  ./run_pipeline.sh

EOF
    exit 0
}

parse_args() {
    while [[ $# -gt 0 ]]; do
        case $1 in
            --skip-export)
                SKIP_EXPORT=true
                shift
                ;;
            --diagrams-only)
                DIAGRAMS_ONLY=true
                SKIP_EXPORT=true
                shift
                ;;
            --dry-run)
                DRY_RUN=true
                shift
                ;;
            --verbose)
                VERBOSE=true
                shift
                ;;
            --help|-h)
                show_help
                ;;
            *)
                log_error "Unknown option: $1"
                echo "Use --help for usage information"
                exit 1
                ;;
        esac
    done
}

check_prerequisites() {
    log_step "Checking prerequisites..."

    # Check Python
    if ! command -v python3 &>/dev/null; then
        log_error "Python 3 is not installed"
        exit 1
    fi
    log_info "Python: $(python3 --version)"

    # Check GraphViz (optional but recommended)
    if command -v dot &>/dev/null; then
        log_info "GraphViz: $(dot -V 2>&1)"
    else
        log_warn "GraphViz not found - PDF generation will be skipped"
    fi

    # Check MQCMDB_HOME
    if [ ! -d "$MQCMDB_HOME" ]; then
        log_error "MQCMDB_HOME directory does not exist: $MQCMDB_HOME"
        exit 1
    fi
    log_info "MQCMDB_HOME: $MQCMDB_HOME"

    # Check required files
    if [ ! -f "$MQCMDB_HOME/orchestrator.py" ]; then
        log_error "orchestrator.py not found in $MQCMDB_HOME"
        exit 1
    fi

    if [ ! -f "$MQCMDB_HOME/db_export.py" ]; then
        log_error "db_export.py not found in $MQCMDB_HOME"
        exit 1
    fi

    # Check for password (UnlockKey or DB_MASTER_PASSWORD)
    # UnlockKey is the preferred CI/CD variable name
    if [ -n "${UnlockKey:-}" ]; then
        export DB_MASTER_PASSWORD="${UnlockKey}"
        log_info "Using UnlockKey from environment"
    fi

    # Check DB_MASTER_PASSWORD (required for database export)
    if [ "$SKIP_EXPORT" = false ] && [ -z "${DB_MASTER_PASSWORD:-}" ]; then
        log_error "No password configured!"
        log_error "Set UnlockKey (recommended) or DB_MASTER_PASSWORD:"
        log_error "  export UnlockKey='your_password'"
        log_error "  export DB_MASTER_PASSWORD='your_password'"
        exit 1
    fi

    log_info "Prerequisites check passed"
}

setup_environment() {
    log_step "Setting up environment..."

    # Create directories
    mkdir -p "$LOG_DIR"
    mkdir -p "$MQCMDB_HOME/output"

    # Set up log file
    local timestamp=$(date '+%Y%m%d_%H%M%S')
    LOG_FILE="$LOG_DIR/pipeline_${timestamp}.log"

    # Load environment file if exists
    if [ -f "$MQCMDB_HOME/.env" ]; then
        log_info "Loading environment from $MQCMDB_HOME/.env"
        set -a
        source "$MQCMDB_HOME/.env"
        set +a
    fi

    # Set Python encoding
    export PYTHONIOENCODING=utf-8
    export PYTHONUNBUFFERED=1

    # Change to working directory
    cd "$MQCMDB_HOME"

    log_info "Working directory: $(pwd)"
    log_info "Log file: $LOG_FILE"

    START_TIME=$(date +%s)
}

cleanup_old_logs() {
    log_step "Cleaning up old logs..."

    # Remove logs older than 7 days
    local deleted_count=0
    if [ -d "$LOG_DIR" ]; then
        while IFS= read -r -d '' file; do
            if [ "$DRY_RUN" = true ]; then
                log_info "[DRY-RUN] Would delete: $file"
            else
                rm -f "$file"
            fi
            ((deleted_count++)) || true
        done < <(find "$LOG_DIR" -name "*.log" -type f -mtime +7 -print0 2>/dev/null)
    fi

    if [ $deleted_count -gt 0 ]; then
        log_info "Cleaned up $deleted_count old log file(s)"
    else
        log_info "No old logs to clean up"
    fi
}

run_database_export() {
    if [ "$SKIP_EXPORT" = true ]; then
        log_info "Skipping database export (--skip-export specified)"
        return 0
    fi

    log_step "Running database export..."

    local cmd="python3 db_export.py --profile $MQCMDB_PROFILE --batch"

    if [ "$DRY_RUN" = true ]; then
        log_info "[DRY-RUN] Would execute: $cmd"
        return 0
    fi

    if [ "$VERBOSE" = true ]; then
        $cmd 2>&1 | tee -a "$LOG_FILE"
    else
        $cmd >> "$LOG_FILE" 2>&1
    fi

    local exit_code=${PIPESTATUS[0]:-$?}
    if [ $exit_code -ne 0 ]; then
        log_error "Database export failed with exit code: $exit_code"
        return $exit_code
    fi

    log_info "Database export completed successfully"
    return 0
}

run_orchestrator() {
    log_step "Running processing pipeline..."

    local cmd="python3 cli.py run"
    if [ "$DIAGRAMS_ONLY" = true ]; then
        cmd="python3 cli.py diagrams"
    fi

    if [ "$DRY_RUN" = true ]; then
        log_info "[DRY-RUN] Would execute: $cmd"
        return 0
    fi

    if [ "$VERBOSE" = true ]; then
        $cmd 2>&1 | tee -a "$LOG_FILE"
    else
        $cmd >> "$LOG_FILE" 2>&1
    fi

    local exit_code=${PIPESTATUS[0]:-$?}
    if [ $exit_code -ne 0 ]; then
        log_error "Pipeline processing failed with exit code: $exit_code"
        return $exit_code
    fi

    log_info "Pipeline processing completed successfully"
    return 0
}

print_summary() {
    local end_time=$(date +%s)
    local duration=$((end_time - START_TIME))
    local minutes=$((duration / 60))
    local seconds=$((duration % 60))

    echo ""
    echo "========================================================================"
    if [ $EXIT_CODE -eq 0 ]; then
        echo -e "${GREEN}Pipeline completed successfully${NC}"
    else
        echo -e "${RED}Pipeline completed with errors (exit code: $EXIT_CODE)${NC}"
    fi
    echo "========================================================================"
    echo ""
    echo "Duration: ${minutes}m ${seconds}s"
    echo "Log file: $LOG_FILE"
    echo ""

    if [ $EXIT_CODE -eq 0 ]; then
        echo "Output files:"
        echo "  - Data:     $MQCMDB_HOME/output/data/"
        echo "  - Diagrams: $MQCMDB_HOME/output/diagrams/"
        echo "  - Reports:  $MQCMDB_HOME/output/reports/"
        echo "  - Exports:  $MQCMDB_HOME/output/exports/"
        echo ""

        # Show recent reports
        if [ -d "$MQCMDB_HOME/output/reports" ]; then
            echo "Recent reports:"
            ls -lt "$MQCMDB_HOME/output/reports"/*.html 2>/dev/null | head -3 | awk '{print "  - " $NF}'
        fi
    else
        echo "Check the log file for details:"
        echo "  tail -100 $LOG_FILE"
    fi
    echo ""
}

send_notification() {
    # Email notification using Python send_email.py utility
    # Configure paths and recipients below

    # Email configuration
    local EMAIL_SCRIPT="${MQCMDB_HOME}/tools/send_email.py"
    local EMAIL_CONFIG="${EMAIL_CONFIG_FILE:-/etc/mqcmdb/email_config.ini}"
    local EMAIL_TO="${EMAIL_RECIPIENTS:-ops-team@company.com}"
    local EMAIL_FROM="${SMTP_FROM:-mqcmdb@company.com}"

    # Check if email is enabled
    if [ "${EMAIL_ENABLED:-false}" != "true" ]; then
        log_info "Email notifications disabled (set EMAIL_ENABLED=true to enable)"
        return 0
    fi

    # Check if email script exists
    if [ ! -f "$EMAIL_SCRIPT" ]; then
        log_warn "Email script not found: $EMAIL_SCRIPT"
        return 1
    fi

    local timestamp=$(date '+%Y-%m-%d %H:%M:%S')
    local subject=""
    local body=""

    if [ $EXIT_CODE -eq 0 ]; then
        subject="[MQ CMDB] Pipeline Completed Successfully - $timestamp"
        body="MQ CMDB Pipeline completed successfully.

Timestamp: $timestamp
Duration: ${1:-unknown}
Log file: $LOG_FILE

Output files:
  - Data:     $MQCMDB_HOME/output/data/
  - Diagrams: $MQCMDB_HOME/output/diagrams/
  - Reports:  $MQCMDB_HOME/output/reports/
  - Exports:  $MQCMDB_HOME/output/exports/

--
MQ CMDB Automation System"
    else
        subject="[MQ CMDB] Pipeline FAILED - $timestamp"
        body="MQ CMDB Pipeline FAILED with exit code: $EXIT_CODE

Timestamp: $timestamp
Log file: $LOG_FILE

Please check the log file for details:
  tail -100 $LOG_FILE

--
MQ CMDB Automation System"
    fi

    log_info "Sending email notification to: $EMAIL_TO"

    # Build command
    local cmd="python3 \"$EMAIL_SCRIPT\" --from \"$EMAIL_FROM\" --to $EMAIL_TO --subject \"$subject\" --body \"$body\""

    # Add config file if exists
    if [ -f "$EMAIL_CONFIG" ]; then
        cmd="python3 \"$EMAIL_SCRIPT\" --config \"$EMAIL_CONFIG\" --from \"$EMAIL_FROM\" --to $EMAIL_TO --subject \"$subject\" --body \"$body\""
    fi

    # Attach log file if it exists and is not too large (< 1MB)
    if [ -f "$LOG_FILE" ]; then
        local log_size=$(stat -f%z "$LOG_FILE" 2>/dev/null || stat -c%s "$LOG_FILE" 2>/dev/null || echo "0")
        if [ "$log_size" -lt 1048576 ]; then
            cmd="$cmd --attach \"$LOG_FILE\""
        fi
    fi

    # Execute
    if eval $cmd 2>&1; then
        log_info "Email notification sent successfully"
    else
        log_warn "Failed to send email notification"
    fi
}

cleanup() {
    # Cleanup function called on exit
    local exit_code=$?

    if [ $exit_code -ne 0 ] && [ "$DRY_RUN" = false ]; then
        log_error "Pipeline terminated with exit code: $exit_code"
    fi

    EXIT_CODE=$exit_code

    # Calculate duration for notification
    local end_time=$(date +%s)
    local duration=$((end_time - START_TIME))
    local minutes=$((duration / 60))
    local seconds=$((duration % 60))
    local duration_str="${minutes}m ${seconds}s"

    print_summary
    send_notification "$duration_str"
}

#-------------------------------------------------------------------------------
# Main
#-------------------------------------------------------------------------------

main() {
    # Set up trap for cleanup
    trap cleanup EXIT

    # Parse command line arguments
    parse_args "$@"

    # Print banner
    print_banner

    # Run pipeline steps
    check_prerequisites
    setup_environment
    cleanup_old_logs
    run_database_export
    run_orchestrator

    log_info "Pipeline execution completed"
}

# Run main function
main "$@"
